package Modelo;

/**
 * Usuario generated by hbm2java
 */
public class Usuario  implements java.io.Serializable {


     private int claveUsuario, agente;
     private String tipo;

    public int getAgente() {
        return agente;
    }

    public void setAgente(int agente) {
        this.agente = agente;
    }

    public String getTipo() {
        return this.tipo;
    }

    public void setTipo(String tipo) {
        this.tipo = tipo;
    }
     private String nombre,usuario;

    public String getUsuario() {
        return this.usuario;
    }

    public void setUsuario(String usuario) {
        this.usuario = usuario;
    }
     private String pass;

    public Usuario() {
    }

	
    public Usuario(int claveUsuario) {
        this.claveUsuario = claveUsuario;
    }   
    public int getClaveUsuario() {
        return this.claveUsuario;
    }
    
    public void setClaveUsuario(int claveUsuario) {
        this.claveUsuario = claveUsuario;
    }
    public String getNombre() {
        return this.nombre;
    }
    
    public void setNombre(String nombre) {
        this.nombre = nombre;
    }
    public String getPass() {
        return this.pass;
    }
    
    public void setPass(String pass) {
        this.pass = pass;
    }




}


